### ISSUE TITLE
SmartUp - Migrate to Github

### ISSUE THREAD

**Issue by MinadakisNikos** [swiss-art-research-net/rdmi#16]
Create a local copy of the platform and commit our templates / fields

**Comment by ncarboni** [comment]
**Task Update**

**Comment by ymark** [comment]
The new instance of the platform (for rds) has been deployed at https://rds.swissartresearch.net/.

In order to proceed with the git integration, we have to create the appropriate git repositories. 
I suppose that we will create them under https://github.com/swiss-art-research-net. Right? 

If so, @ncarboni could you please create the repositories and add us as collaborators? Alternatively, you can grant us permissions to do so (create the repositories and push updates)

**Comment by ncarboni** [comment]
@ymark can we just use this repository or it is necessary a specific one just for that?

**Comment by ymark** [comment]
I guess we can (I do not see emerging conflicts with respect to the current contents of the repository).
We'll create a branch and move on.

Thanks

**Comment by ncarboni** [comment]
I think we can close this. Feel free to re-open if necessary
