### ISSUE TITLE
Outline possible Workpackages/Requirement Definition for next Phase

### ISSUE THREAD

**Issue by thomashaensli** [swiss-art-research-net/rdmi#8]
1. start from Nikos' proposal and flesh out hat actually needs to be done @thomashaensli  @ncarboni @matteoLorenzini 

2. assign priorities

3. send it back to @MinadakisNikos to make an effort estimation

**Comment by MinadakisNikos** [comment]
Just a reminder for this. The ppt is here:
https://drive.google.com/open?id=1aGYbmtBURpn_jV3oKS9I8pHTXqX-_Okp

**Comment by matteoLorenzini** [comment]
Here a bullet list about the activities I'm working on:
* Quality control
    * Check and align the mapping stucture  respect to the definitions provided by CRMarchi
    * Filed(s) refinement (Ouvre, Project and Built Work)
* Mapping
    * Mappings implementation (3M)
    * Data transformation (X3M)
    * Data ingestion (RS)
* Usability
    * UX/UI map
    * Template and fileds definition (Ouvre, Project and Built Work)
    * Template and fields refinement (Ouvre, Project and Built Work)

Since our RS environment it is increasing I would suggest the development of a UI map in order to have a clear view about the structure of the different components (pages, template etc. etc.). If you agree I can do it. 

I did not specify (in the bullet list under Usability) the Development of the landing page which is done by Smartup.

**Comment by ncarboni** [comment]
The WP requirements seemed to be done. I close, reopen if necessary
